### ISSUE TITLE
Should permissions be removed from the library ('memtrip-picsy')?

### ISSUE THREAD

**Issue by oseparovic** [samkirton/picsy#2]
The default behaviour of gradle is to merge manifests as far as I know. For that reason including the following permissions might be undesirable:

```
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.camera.autofocus" />
```

I realize many things in your lib require these permissions to function but some also do not (like the `CapturePhotoUtils` class that I am using). Should it be perhaps left up to the user of the lib to define their permission in their own manifest based on what components they're using?

Currently if you're using the lib and building with gradle you'll have to manually modify the lib to remove these permissions if you aren't using them (and don't use them in your app already). Android users hate approving new permissions and every time you add one there's a good chance you'll suffer a slight userbase decrease due to that prompt.

Thoughts?

**Comment by samkirton** [comment]
Removing the permissions sounds like the best approach. Thanks for your valuable input!

**Comment by oseparovic** [comment]
Ok sounds good!

I made a pull request earlier (https://github.com/samkirton/picsy/pull/1) that I have since updated to remove those permissions as well. The pull request also removes a lot of generated files from the lib and ignores them via gitignore. I also took a stab at setting up a "How to use" section in the readme.

Please review and let me know :)
